# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: governance_prep_processed.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="governance_prep_processed.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x1fgovernance_prep_processed.proto";\n\x17GovernancePrepProcessed\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07is_prep\x18\x02 \x01(\x08\x62\x06proto3'
    ),
)


_GOVERNANCEPREPPROCESSED = _descriptor.Descriptor(
    name="GovernancePrepProcessed",
    full_name="GovernancePrepProcessed",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="address",
            full_name="GovernancePrepProcessed.address",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="is_prep",
            full_name="GovernancePrepProcessed.is_prep",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=35,
    serialized_end=94,
)

DESCRIPTOR.message_types_by_name["GovernancePrepProcessed"] = _GOVERNANCEPREPPROCESSED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GovernancePrepProcessed = _reflection.GeneratedProtocolMessageType(
    "GovernancePrepProcessed",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GOVERNANCEPREPPROCESSED,
        __module__="governance_prep_processed_pb2"
        # @@protoc_insertion_point(class_scope:GovernancePrepProcessed)
    ),
)
_sym_db.RegisterMessage(GovernancePrepProcessed)


# @@protoc_insertion_point(module_scope)
