"""add block delegations

Revision ID: 02abf7170d28
Revises: 99325d6a882a
Create Date: 2022-02-14 13:50:27.117887

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "02abf7170d28"
down_revision = "99325d6a882a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("delegations", sa.Column("last_updated_block", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_delegations_last_updated_block"),
        "delegations",
        ["last_updated_block"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delegations_last_updated_block"), table_name="delegations")
    op.drop_column("delegations", "last_updated_block")
    # ### end Alembic commands ###
