"""v0.2.1-add-bonded-power

Revision ID: 032e3aa62920
Revises: 0c6f9b15807b
Create Date: 2023-03-21 15:08:27.023354

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "032e3aa62920"
down_revision = "0c6f9b15807b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preps", sa.Column("bonded", sa.Float(), nullable=True))
    op.add_column("preps", sa.Column("power", sa.Float(), nullable=True))
    op.add_column("preps", sa.Column("failure_count", sa.Integer(), nullable=True))
    op.add_column("preps", sa.Column("penalties", sa.Integer(), nullable=True))
    op.drop_column("preps", "missed_periods")
    op.drop_column("preps", "missed_blocks")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "preps", sa.Column("missed_blocks", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "preps", sa.Column("missed_periods", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("preps", "penalties")
    op.drop_column("preps", "failure_count")
    op.drop_column("preps", "power")
    op.drop_column("preps", "bonded")
    # ### end Alembic commands ###
