"""v0.2.1-drop-bonded-power

Revision ID: 0c6f9b15807b
Revises: 71cdf838a3b6
Create Date: 2023-03-17 09:05:45.345645

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c6f9b15807b"
down_revision = "71cdf838a3b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "bonded")
    op.drop_column("preps", "power")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preps", sa.Column("power", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("preps", sa.Column("bonded", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
