"""proposals

Revision ID: 0d3a8918c97f
Revises: ff491b21f24d
Create Date: 2021-10-25 15:05:01.556311

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d3a8918c97f"
down_revision = "ff491b21f24d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposals",
        sa.Column("contents_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("proposer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proposer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_block_height", sa.Integer(), nullable=True),
        sa.Column("end_block_height", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agree_count", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agree_amount", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("disagree_count", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("disagree_amount", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("no_vote_count", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("no_vote_amount", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proposals_id"), "proposals", ["id"], unique=False)
    op.add_column("preps", sa.Column("sponsored_cps_grants", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "sponsored_cps_grants")
    op.drop_index(op.f("ix_proposals_id"), table_name="proposals")
    op.drop_table("proposals")
    # ### end Alembic commands ###
