"""v0.7.1-wage

Revision ID: 2945fc0e4d84
Revises: 694432f3c689
Create Date: 2024-03-21 19:55:21.279876

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2945fc0e4d84'
down_revision = '694432f3c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
