"""v0.7.1-apys

Revision ID: 345e65377c3d
Revises: 2945fc0e4d84
Create Date: 2024-03-23 15:33:47.765666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '345e65377c3d'
down_revision = '2945fc0e4d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apy_time', 'total_wage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('apy_time', 'active_preps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('apy_time', 'cps_apy')
    op.drop_column('apy_time', 'relay_apy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apy_time', sa.Column('relay_apy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('apy_time', sa.Column('cps_apy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('apy_time', 'active_preps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apy_time', 'total_wage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
