"""init

Revision ID: 3b7e032d2384
Revises:
Create Date: 2021-10-01 02:25:02.820531

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b7e032d2384"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prep",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("p2p_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("node_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("penalty", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("grade", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_updated_block", sa.Integer(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.Column("created_block", sa.Integer(), nullable=True),
        sa.Column("created_timestamp", sa.Integer(), nullable=True),
        sa.Column("logo_256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("logo_1024", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("logo_svg", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("steemit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("twitter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("youtube", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("facebook", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reddit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keybase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("telegram", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("wechat", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("server_country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("server_city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("server_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(op.f("ix_prep_address"), "prep", ["address"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prep_address"), table_name="prep")
    op.drop_table("prep")
    # ### end Alembic commands ###
