"""remove bondedDelegation

Revision ID: 4400883a1249
Revises: ffc4d8b28524
Create Date: 2021-12-27 00:34:33.252574

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4400883a1249"
down_revision = "ffc4d8b28524"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "bondedDelegation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "preps", sa.Column("bondedDelegation", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
