"""v0.8.0-commission-stats

Revision ID: 694432f3c689
Revises: 76a52d8cadde
Create Date: 2024-03-18 16:32:55.883578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '694432f3c689'
down_revision = '76a52d8cadde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_time',
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('commission_rate_average', sa.Float(), nullable=False),
    sa.Column('commission_rate_weighted_average', sa.Float(), nullable=False),
    sa.Column('commission_rate_median', sa.Float(), nullable=False),
    sa.Column('commission_rate_max', sa.Float(), nullable=False),
    sa.Column('commission_rate_min', sa.Float(), nullable=False),
    sa.Column('commission_rate_stdev', sa.Float(), nullable=False),
    sa.Column('commission_rate_weighted_stdev', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_average', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_weighted_average', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_median', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_max', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_min', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_stdev', sa.Float(), nullable=False),
    sa.Column('max_commission_change_rate_weighted_stdev', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_average', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_weighted_average', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_median', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_max', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_min', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_stdev', sa.Float(), nullable=False),
    sa.Column('max_commission_rate_weighted_stdev', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_commission_time_height'), 'commission_time', ['height'], unique=False)
    op.add_column('apy_time', sa.Column('total_wage', sa.Float(), nullable=False))
    op.add_column('apy_time', sa.Column('active_preps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apy_time', 'active_preps')
    op.drop_column('apy_time', 'total_wage')
    op.drop_index(op.f('ix_commission_time_height'), table_name='commission_time')
    op.drop_table('commission_time')
    # ### end Alembic commands ###
