"""v0.2.0-add-blocks

Revision ID: 71cdf838a3b6
Revises: 02abf7170d28
Create Date: 2023-03-09 00:26:36.164636

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "71cdf838a3b6"
down_revision = "02abf7170d28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_delegations_address", table_name="delegations")
    op.drop_index("ix_delegations_last_updated_block", table_name="delegations")
    op.drop_index("ix_delegations_prep_address", table_name="delegations")
    op.drop_index("ix_delegations_value", table_name="delegations")
    op.add_column(
        "preps", sa.Column("metrics_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("preps", sa.Column("missed_blocks", sa.Integer(), nullable=True))
    op.add_column("preps", sa.Column("missed_periods", sa.Integer(), nullable=True))
    op.alter_column("preps", "cps_governance", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index("ix_preps_address", table_name="preps")
    op.drop_index("ix_proposals_id", table_name="proposals")
    op.drop_index("ix_rewards_block", table_name="rewards")
    op.drop_index("ix_rewards_iscore", table_name="rewards")
    op.drop_index("ix_rewards_timestamp", table_name="rewards")
    op.drop_index("ix_rewards_tx_hash", table_name="rewards")
    op.drop_index("ix_rewards_value", table_name="rewards")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_rewards_value", "rewards", ["value"], unique=False)
    op.create_index("ix_rewards_tx_hash", "rewards", ["tx_hash"], unique=False)
    op.create_index("ix_rewards_timestamp", "rewards", ["timestamp"], unique=False)
    op.create_index("ix_rewards_iscore", "rewards", ["iscore"], unique=False)
    op.create_index("ix_rewards_block", "rewards", ["block"], unique=False)
    op.create_index("ix_proposals_id", "proposals", ["id"], unique=False)
    op.create_index("ix_preps_address", "preps", ["address"], unique=False)
    op.alter_column("preps", "cps_governance", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("preps", "missed_periods")
    op.drop_column("preps", "missed_blocks")
    op.drop_column("preps", "metrics_endpoint")
    op.create_index("ix_delegations_value", "delegations", ["value"], unique=False)
    op.create_index("ix_delegations_prep_address", "delegations", ["prep_address"], unique=False)
    op.create_index(
        "ix_delegations_last_updated_block", "delegations", ["last_updated_block"], unique=False
    )
    op.create_index("ix_delegations_address", "delegations", ["address"], unique=False)
    # ### end Alembic commands ###
