"""v0.6.0-stats-preps-bonders-stakers-stats

Revision ID: 86f2a1c7a3b2
Revises: fc456dcaa570
Create Date: 2023-11-15 21:24:28.351350

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "86f2a1c7a3b2"
down_revision = "fc456dcaa570"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("stakers", sa.Integer(), nullable=False),
        sa.Column("bonders", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.add_column("preps", sa.Column("stakers", sa.Integer(), nullable=True))
    op.add_column("preps", sa.Column("bonders", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "bonders")
    op.drop_column("preps", "stakers")
    op.drop_table("stats")
    # ### end Alembic commands ###
