"""add staking cron

Revision ID: 92b906e51bf3
Revises: 3b7e032d2384
Create Date: 2021-10-08 02:46:50.327019

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "92b906e51bf3"
down_revision = "3b7e032d2384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prep", sa.Column("voted", sa.Float(), nullable=True))
    op.add_column("prep", sa.Column("voting_power", sa.Float(), nullable=True))
    op.add_column("prep", sa.Column("delegated", sa.Float(), nullable=True))
    op.add_column("prep", sa.Column("stake", sa.Float(), nullable=True))
    op.add_column("prep", sa.Column("irep", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prep", "irep")
    op.drop_column("prep", "stake")
    op.drop_column("prep", "delegated")
    op.drop_column("prep", "voting_power")
    op.drop_column("prep", "voted")
    # ### end Alembic commands ###
