"""v0.9.0-sort-preps

Revision ID: 939ec864a967
Revises: e814478da827
Create Date: 2024-07-24 19:26:57.620694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '939ec864a967'
down_revision = 'e814478da827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preps', sa.Column('bond_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preps', 'bond_percent')
    # ### end Alembic commands ###
