"""v0.4.0-rewards

Revision ID: 9e1abdbf7641
Revises: 032e3aa62920
Create Date: 2023-07-01 20:05:37.052209

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e1abdbf7641"
down_revision = "032e3aa62920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claims")
    op.add_column("preps", sa.Column("reward_monthly", sa.Float(), nullable=True))
    op.add_column("preps", sa.Column("reward_monthly_usd", sa.Float(), nullable=True))
    op.add_column("preps", sa.Column("reward_daily", sa.Float(), nullable=True))
    op.add_column("preps", sa.Column("reward_daily_usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "reward_daily_usd")
    op.drop_column("preps", "reward_daily")
    op.drop_column("preps", "reward_monthly_usd")
    op.drop_column("preps", "reward_monthly")
    op.create_table(
        "claims",
        sa.Column("claim_index", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("end_block_number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("is_claimed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_head", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("job_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("start_block_number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("claim_index", "job_hash", name="claims_pkey"),
    )
    # ### end Alembic commands ###
