"""bond addition

Revision ID: ad46aa4e5386
Revises: 0d3a8918c97f
Create Date: 2021-11-14 22:26:08.247272

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad46aa4e5386"
down_revision = "0d3a8918c97f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preps", sa.Column("bonded", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "preps", sa.Column("bondedDelegation", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "bondedDelegation")
    op.drop_column("preps", "bonded")
    # ### end Alembic commands ###
