"""v0.6.0-mod-apy

Revision ID: b2bff849e370
Revises: 86f2a1c7a3b2
Create Date: 2023-11-21 14:17:37.255763

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2bff849e370"
down_revision = "86f2a1c7a3b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apy_time", sa.Column("total_bonded", sa.Float(), nullable=False))
    op.add_column("apy_time", sa.Column("total_power", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apy_time", "total_power")
    op.drop_column("apy_time", "total_bonded")
    # ### end Alembic commands ###
