"""v0.2.3-add-delegator

Revision ID: b8d765a31043
Revises: 032e3aa62920
Create Date: 2023-04-27 03:20:18.780843

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8d765a31043"
down_revision = "032e3aa62920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claims")
    op.add_column(
        "delegations", sa.Column("delegator", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_delegations_delegator"), "delegations", ["delegator"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delegations_delegator"), table_name="delegations")
    op.drop_column("delegations", "delegator")
    op.create_table(
        "claims",
        sa.Column("claim_index", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("end_block_number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("is_claimed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_head", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("job_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("start_block_number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("claim_index", "job_hash", name="claims_pkey"),
    )
    # ### end Alembic commands ###
