"""init

Revision ID: cb0f0846c1f6
Revises: 
Create Date: 2021-09-24 17:42:15.997157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cb0f0846c1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prep',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('p2p_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated_block', sa.Integer(), nullable=True),
    sa.Column('last_updated_timestamp', sa.Integer(), nullable=True),
    sa.Column('created_block', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.Integer(), nullable=True),
    sa.Column('logo_256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_1024', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_svg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steemit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('facebook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reddit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keybase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wechat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('server_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('server_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('server_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_prep_address'), 'prep', ['address'], unique=False)
    op.create_index(op.f('ix_prep_api_endpoint'), 'prep', ['api_endpoint'], unique=False)
    op.create_index(op.f('ix_prep_city'), 'prep', ['city'], unique=False)
    op.create_index(op.f('ix_prep_country'), 'prep', ['country'], unique=False)
    op.create_index(op.f('ix_prep_created_block'), 'prep', ['created_block'], unique=False)
    op.create_index(op.f('ix_prep_created_timestamp'), 'prep', ['created_timestamp'], unique=False)
    op.create_index(op.f('ix_prep_details'), 'prep', ['details'], unique=False)
    op.create_index(op.f('ix_prep_email'), 'prep', ['email'], unique=False)
    op.create_index(op.f('ix_prep_facebook'), 'prep', ['facebook'], unique=False)
    op.create_index(op.f('ix_prep_github'), 'prep', ['github'], unique=False)
    op.create_index(op.f('ix_prep_keybase'), 'prep', ['keybase'], unique=False)
    op.create_index(op.f('ix_prep_last_updated_block'), 'prep', ['last_updated_block'], unique=False)
    op.create_index(op.f('ix_prep_last_updated_timestamp'), 'prep', ['last_updated_timestamp'], unique=False)
    op.create_index(op.f('ix_prep_logo_1024'), 'prep', ['logo_1024'], unique=False)
    op.create_index(op.f('ix_prep_logo_256'), 'prep', ['logo_256'], unique=False)
    op.create_index(op.f('ix_prep_logo_svg'), 'prep', ['logo_svg'], unique=False)
    op.create_index(op.f('ix_prep_name'), 'prep', ['name'], unique=False)
    op.create_index(op.f('ix_prep_node_address'), 'prep', ['node_address'], unique=False)
    op.create_index(op.f('ix_prep_p2p_endpoint'), 'prep', ['p2p_endpoint'], unique=False)
    op.create_index(op.f('ix_prep_reddit'), 'prep', ['reddit'], unique=False)
    op.create_index(op.f('ix_prep_server_city'), 'prep', ['server_city'], unique=False)
    op.create_index(op.f('ix_prep_server_country'), 'prep', ['server_country'], unique=False)
    op.create_index(op.f('ix_prep_server_type'), 'prep', ['server_type'], unique=False)
    op.create_index(op.f('ix_prep_status'), 'prep', ['status'], unique=False)
    op.create_index(op.f('ix_prep_steemit'), 'prep', ['steemit'], unique=False)
    op.create_index(op.f('ix_prep_telegram'), 'prep', ['telegram'], unique=False)
    op.create_index(op.f('ix_prep_twitter'), 'prep', ['twitter'], unique=False)
    op.create_index(op.f('ix_prep_website'), 'prep', ['website'], unique=False)
    op.create_index(op.f('ix_prep_wechat'), 'prep', ['wechat'], unique=False)
    op.create_index(op.f('ix_prep_youtube'), 'prep', ['youtube'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prep_youtube'), table_name='prep')
    op.drop_index(op.f('ix_prep_wechat'), table_name='prep')
    op.drop_index(op.f('ix_prep_website'), table_name='prep')
    op.drop_index(op.f('ix_prep_twitter'), table_name='prep')
    op.drop_index(op.f('ix_prep_telegram'), table_name='prep')
    op.drop_index(op.f('ix_prep_steemit'), table_name='prep')
    op.drop_index(op.f('ix_prep_status'), table_name='prep')
    op.drop_index(op.f('ix_prep_server_type'), table_name='prep')
    op.drop_index(op.f('ix_prep_server_country'), table_name='prep')
    op.drop_index(op.f('ix_prep_server_city'), table_name='prep')
    op.drop_index(op.f('ix_prep_reddit'), table_name='prep')
    op.drop_index(op.f('ix_prep_p2p_endpoint'), table_name='prep')
    op.drop_index(op.f('ix_prep_node_address'), table_name='prep')
    op.drop_index(op.f('ix_prep_name'), table_name='prep')
    op.drop_index(op.f('ix_prep_logo_svg'), table_name='prep')
    op.drop_index(op.f('ix_prep_logo_256'), table_name='prep')
    op.drop_index(op.f('ix_prep_logo_1024'), table_name='prep')
    op.drop_index(op.f('ix_prep_last_updated_timestamp'), table_name='prep')
    op.drop_index(op.f('ix_prep_last_updated_block'), table_name='prep')
    op.drop_index(op.f('ix_prep_keybase'), table_name='prep')
    op.drop_index(op.f('ix_prep_github'), table_name='prep')
    op.drop_index(op.f('ix_prep_facebook'), table_name='prep')
    op.drop_index(op.f('ix_prep_email'), table_name='prep')
    op.drop_index(op.f('ix_prep_details'), table_name='prep')
    op.drop_index(op.f('ix_prep_created_timestamp'), table_name='prep')
    op.drop_index(op.f('ix_prep_created_block'), table_name='prep')
    op.drop_index(op.f('ix_prep_country'), table_name='prep')
    op.drop_index(op.f('ix_prep_city'), table_name='prep')
    op.drop_index(op.f('ix_prep_api_endpoint'), table_name='prep')
    op.drop_index(op.f('ix_prep_address'), table_name='prep')
    op.drop_table('prep')
    # ### end Alembic commands ###
