"""v0.6.0-apys

Revision ID: fc456dcaa570
Revises: 5fd584cbb64d
Create Date: 2023-11-06 16:00:06.703900

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc456dcaa570"
down_revision = "5fd584cbb64d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apy_time",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("i_global", sa.Float(), nullable=False),
        sa.Column("i_voter", sa.Float(), nullable=False),
        sa.Column("i_prep", sa.Float(), nullable=False),
        sa.Column("i_cps", sa.Float(), nullable=False),
        sa.Column("i_relay", sa.Float(), nullable=False),
        sa.Column("staking_apy", sa.Float(), nullable=False),
        sa.Column("prep_apy", sa.Float(), nullable=False),
        sa.Column("cps_apy", sa.Float(), nullable=False),
        sa.Column("relay_apy", sa.Float(), nullable=False),
        sa.Column("total_delegated", sa.Float(), nullable=False),
        sa.Column("total_stake", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apy_time")
    # ### end Alembic commands ###
