"""add cps governance

Revision ID: ffc4d8b28524
Revises: 11b01658b724
Create Date: 2021-12-20 20:28:30.504941

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ffc4d8b28524"
down_revision = "11b01658b724"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preps", sa.Column("cps_governance", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preps", "cps_governance")
    # ### end Alembic commands ###
